# Write your MySQL query statement below
WITH CTE AS(
    SELECT D.NAME AS DEPARTMENT, E.NAME, E.SALARY, DENSE_RANK() OVER (PARTITION BY E.DEPARTMENTID ORDER BY E.SALARY DESC) AS RNK FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
)
SELECT DEPARTMENT, NAME AS EMPLOYEE, SALARY FROM CTE WHERE RNK <=3;